name: multiomics_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - pandas
  - statsmodels
  - openpyxl
  - scikit-learn
  - scikit-image
  - scanpy
  - muon
  - mofapy2
  - matplotlib
  - seaborn
  - anndata
  - pooch
  - pip
  - pip:
    - lifelines
    - scikit-survival
    - pydeseq2